#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:

usage(){
echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
}
pathToFile="$1"
Ip="$2"
userName="$3"
pathToSsh="$4"
if [ "$#" -eq 4 ];then
	scp -o StrictHostKeyChecking=no -i "$pathToSsh" "$pathToFile" "$userName@$Ip":~/
else
	usage
fi
