#!/usr/bin/env bash
# file to install nginx on a server
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx

sudo echo 'Hello World!' >/var/www/html/index.nginx-debian.html
sudo service nginx start
