#!/bin/bash

# Display a list of currently running processes with hierarchy
echo "PID  PPID  USER    COMMAND"

# Use ps command to list all processes in a user-oriented format
ps axo pid,ppid,user,cmd --forest

