#!/usr/bin/env bash
# Write a Bash script that creates an RSA key pair.
#+ Requirements:
#+ Name of the created private key must be school
#+ Number of bits in the created key to be created 4096
#+ The created key must be protected by the passphrase

key_name="school"
key_bits=4096
key_passphrase="betty"
ssh-keygen -t rsa -b $key_bits -f $key_name -N $key_passphrase
